DROP DATABASE IF EXISTS PARTICLEDATA;
CREATE DATABASE PARTICLEDATA;
USE PARTICLEDATA;

CREATE TABLE MAIN (
    PM10 FLOAT,
    PM25 FLOAT,
    Temperature FLOAT,
    Humidity FLOAT,
    Date DATE,
    Time TIME

) ;