DROP DATABASE IF EXISTS PARTICLEDATA;
CREATE DATABASE PARTICLEDATA;
USE PARTICLEDATA;

CREATE TABLE PARTICLEDATA (
    PM10 FLOAT,
    PM25 FLOAT,
    Temperature FLOAT,
    Humidity FLOAT,
    Date DATE,
    Time TIME,

);